#!/usr/bin/env node

/**
 * Content Handling for Release Announcements
 *
 * Content is generated by Claude Code before running this script.
 * This module handles reading content from environment variables or files.
 */

/**
 * @typedef {Object} ReleaseInfo
 * @property {string} version - Release version (e.g., "2.3.4")
 * @property {string} body - Raw release notes markdown
 * @property {string} tagName - Git tag name
 * @property {string} url - GitHub release URL
 * @property {string} publishedAt - ISO date string
 */

/**
 * @typedef {Object} GeneratedContent
 * @property {Object} discord - Discord-specific content
 * @property {string} discord.title - Embed title
 * @property {string} discord.description - Embed description
 * @property {string[]} discord.highlights - Key highlights as bullet points
 * @property {Object} twitter - Twitter-specific content
 * @property {string} twitter.text - Main tweet text (max 280 chars)
 * @property {string[]} twitter.hashtags - Hashtags to append to main tweet
 * @property {string[]} [twitter.thread] - Additional tweets for thread (each max 280 chars)
 * @property {Object} www - Website content
 * @property {string} www.homeChangelog - Summary for home page
 * @property {string} www.fullChangelog - Full changelog entry markdown
 */

/**
 * Get content from environment variable (set by Claude Code)
 * @param {ReleaseInfo} releaseInfo - Release information
 * @param {Object} options - Options
 * @param {boolean} options.dryRun - If true, return mock content
 * @returns {Promise<GeneratedContent>}
 */
export async function generateContent(releaseInfo, options = {}) {
  if (options.dryRun) {
    console.log('🔵 [DRY RUN] Using mock content')
    return getMockContent(releaseInfo)
  }

  // Try to read content from environment variable (JSON)
  const contentJson = process.env.RELEASE_CONTENT
  if (contentJson) {
    try {
      const content = JSON.parse(contentJson)
      console.log('✅ Using provided release content')
      return content
    } catch (error) {
      console.error('❌ Failed to parse RELEASE_CONTENT:', error.message)
    }
  }

  // Try to read from file
  const fs = await import('fs')
  const path = await import('path')
  const { fileURLToPath } = await import('url')

  const __filename = fileURLToPath(import.meta.url)
  const __dirname = path.dirname(__filename)
  const contentFilePath = path.join(__dirname, '../../.release-content.json')

  if (fs.existsSync(contentFilePath)) {
    try {
      const content = JSON.parse(fs.readFileSync(contentFilePath, 'utf8'))
      console.log('✅ Using content from .release-content.json')
      // Clean up the file after reading
      fs.unlinkSync(contentFilePath)
      return content
    } catch (error) {
      console.error('❌ Failed to read .release-content.json:', error.message)
    }
  }

  // Fall back to template content
  console.log('ℹ️  No pre-generated content found, using template')
  return getFallbackContent(releaseInfo)
}

/**
 * Get mock content for dry runs
 * @param {ReleaseInfo} releaseInfo
 * @returns {GeneratedContent}
 */
function getMockContent(releaseInfo) {
  return {
    discord: {
      title: `🚀 SonicJS v${releaseInfo.version} Released! [DRY RUN]`,
      description: 'This is a dry run - no actual content was generated.',
      highlights: [
        '[DRY RUN] Highlight 1',
        '[DRY RUN] Highlight 2',
        '[DRY RUN] Highlight 3'
      ]
    },
    twitter: {
      text: `[DRY RUN] SonicJS v${releaseInfo.version} is here! Check out the latest release.`,
      hashtags: ['SonicJS', 'DryRun']
    },
    www: {
      homeChangelog: `[DRY RUN] v${releaseInfo.version} - Test release`,
      fullChangelog: `## v${releaseInfo.version} [DRY RUN]\n\n_This is a dry run test._\n\n### Changes\n- Test change 1\n- Test change 2`
    }
  }
}

/**
 * Get fallback content when no pre-generated content is available
 * @param {ReleaseInfo} releaseInfo
 * @returns {GeneratedContent}
 */
function getFallbackContent(releaseInfo) {
  const version = releaseInfo.version
  const body = releaseInfo.body || 'Bug fixes and improvements.'

  // Extract first few lines for highlights
  const lines = body.split('\n').filter(line => line.trim().startsWith('-') || line.trim().startsWith('*'))
  const highlights = lines.slice(0, 4).map(line => line.replace(/^[-*]\s*/, '').trim())

  // Build thread tweets from highlights
  const thread = []
  if (highlights.length > 0) {
    thread.push(`✨ What's new in v${version}:\n\n${highlights.map((h, i) => `${i + 1}. ${h}`).join('\n')}`)
  }
  thread.push(`📦 Get started:\nnpx create-sonicjs@latest my-app\n\nSonicJS is 6x faster than Node/Express and deploys globally on Cloudflare Workers in seconds.`)
  thread.push(`⭐ If you find SonicJS useful, please star us on GitHub!\n\nhttps://github.com/lane711/sonicjs\n\nYour support helps us keep improving the project!`)

  return {
    discord: {
      title: `🚀 SonicJS v${version} Released!`,
      description: `A new version of SonicJS has been published with improvements and fixes.`,
      highlights: highlights.length > 0 ? highlights : ['Various improvements and bug fixes']
    },
    twitter: {
      text: `🚀 SonicJS v${version} is now available! The open-source headless CMS for Cloudflare Workers just got better.`,
      hashtags: ['SonicJS', 'CloudflareWorkers', 'HeadlessCMS', 'OpenSource'],
      thread
    },
    www: {
      homeChangelog: `v${version} - ${new Date().toISOString().split('T')[0]}`,
      fullChangelog: `## v${version} - ${new Date().toISOString().split('T')[0]}\n\n${body}`
    }
  }
}

/**
 * Read release info from environment or package.json
 * @returns {Promise<ReleaseInfo>}
 */
export async function getReleaseInfo() {
  // Try to get from environment (GitHub Actions)
  if (process.env.RELEASE_TAG && process.env.RELEASE_BODY) {
    return {
      version: process.env.RELEASE_TAG.replace(/^v/, ''),
      tagName: process.env.RELEASE_TAG,
      body: process.env.RELEASE_BODY,
      url: process.env.RELEASE_URL || `https://github.com/lane711/sonicjs/releases/tag/${process.env.RELEASE_TAG}`,
      publishedAt: process.env.RELEASE_PUBLISHED_AT || new Date().toISOString()
    }
  }

  // Fall back to reading from package.json
  const fs = await import('fs')
  const path = await import('path')
  const { fileURLToPath } = await import('url')

  const __filename = fileURLToPath(import.meta.url)
  const __dirname = path.dirname(__filename)
  const rootDir = path.join(__dirname, '../..')
  const corePackageJsonPath = path.join(rootDir, 'packages/core/package.json')

  const corePackageJson = JSON.parse(fs.readFileSync(corePackageJsonPath, 'utf8'))
  const version = corePackageJson.version

  return {
    version,
    tagName: `v${version}`,
    body: process.env.RELEASE_BODY || '',
    url: `https://github.com/lane711/sonicjs/releases/tag/v${version}`,
    publishedAt: new Date().toISOString()
  }
}
