/**
 * Plugin Registry
 *
 * This file is AUTO-GENERATED by scripts/generate-plugin-registry.mjs
 * DO NOT EDIT MANUALLY - your changes will be overwritten!
 *
 * Generated: 2025-10-20T19:30:51.844Z
 * Source: All manifest.json files in src/plugins/
 */

export interface PluginManifest {
  id: string
  name: string
  version: string
  description: string
  author: string
  homepage?: string
  repository?: string
  license?: string
  category: string
  tags?: string[]
  dependencies?: string[]
  settings?: Record<string, any>
  hooks?: Record<string, string>
  routes?: Array<{
    path: string
    method: string
    handler: string
    description?: string
  }>
  permissions?: Record<string, string>
  adminMenu?: {
    label: string
    icon: string
    path: string
    order: number
  }
}

/**
 * Plugin Registry
 * Maps plugin ID to its manifest
 */
export const PLUGIN_REGISTRY: Record<string, PluginManifest> = {
  'core-cache': {
    "id": "core-cache",
    "name": "Cache System",
    "version": "1.0.0-beta.1",
    "description": "Three-tiered caching system with in-memory and KV storage. Provides automatic caching for content, users, media, and API responses with configurable TTL and invalidation patterns.",
    "author": "SonicJS",
    "homepage": "https://sonicjs.com/plugins/cache",
    "repository": "https://github.com/lane711/sonicjs-ai/tree/main/src/plugins/cache",
    "license": "MIT",
    "category": "performance",
    "tags": [
      "cache",
      "performance",
      "optimization",
      "kv",
      "memory"
    ],
    "dependencies": [],
    "settings": {
      "memoryEnabled": {
        "type": "boolean",
        "label": "Enable In-Memory Cache",
        "description": "Fast tier-1 caching in memory (region-specific)",
        "default": true
      },
      "kvEnabled": {
        "type": "boolean",
        "label": "Enable KV Cache",
        "description": "Tier-2 caching in Cloudflare KV (global, persistent)",
        "default": false
      },
      "defaultTTL": {
        "type": "number",
        "label": "Default TTL (seconds)",
        "description": "Default time-to-live for cache entries",
        "default": 3600
      },
      "maxMemorySize": {
        "type": "number",
        "label": "Max Memory Size (MB)",
        "description": "Maximum size of in-memory cache in megabytes",
        "default": 50
      }
    },
    "hooks": {
      "onActivate": "activate",
      "onDeactivate": "deactivate",
      "onConfigure": "configure"
    },
    "routes": [
      {
        "path": "/admin/cache/stats",
        "method": "GET",
        "handler": "getStats",
        "description": "Get cache statistics"
      },
      {
        "path": "/admin/cache/clear",
        "method": "POST",
        "handler": "clearCache",
        "description": "Clear all cache entries"
      },
      {
        "path": "/admin/cache/invalidate",
        "method": "POST",
        "handler": "invalidatePattern",
        "description": "Invalidate cache entries matching pattern"
      }
    ],
    "permissions": {
      "cache.view": "View cache statistics",
      "cache.clear": "Clear cache entries",
      "cache.invalidate": "Invalidate cache patterns"
    }
  },

  'core-analytics': {
    "id": "core-analytics",
    "name": "Analytics & Insights",
    "version": "1.0.0-beta.1",
    "description": "Core analytics system for tracking page views, user behavior, and content performance. Provides dashboards and reports with real-time metrics",
    "author": "SonicJS Team",
    "homepage": "https://sonicjs.com/plugins/core-analytics",
    "repository": "https://github.com/lane711/sonicjs-ai/tree/main/src/plugins/core-plugins",
    "license": "MIT",
    "category": "analytics",
    "tags": [
      "analytics",
      "metrics",
      "tracking",
      "insights",
      "dashboard"
    ],
    "dependencies": [],
    "settings": {
      "trackPageViews": {
        "type": "boolean",
        "label": "Track Page Views",
        "description": "Automatically track page views",
        "default": true
      },
      "trackUserSessions": {
        "type": "boolean",
        "label": "Track User Sessions",
        "description": "Track user session duration and behavior",
        "default": true
      },
      "retentionDays": {
        "type": "number",
        "label": "Data Retention (days)",
        "description": "How long to keep analytics data",
        "default": 90
      }
    },
    "hooks": {
      "onActivate": "activate",
      "onDeactivate": "deactivate"
    },
    "routes": [],
    "permissions": {
      "analytics:view": "View analytics data",
      "analytics:export": "Export analytics reports"
    },
    "adminMenu": {
      "label": "Analytics",
      "icon": "chart-bar",
      "path": "/admin/analytics",
      "order": 50
    }
  },

  'core-auth': {
    "id": "core-auth",
    "name": "Authentication System",
    "version": "1.0.0-beta.1",
    "description": "Core authentication and user management system with role-based access control, session management, and security features",
    "author": "SonicJS Team",
    "homepage": "https://sonicjs.com/plugins/core-auth",
    "repository": "https://github.com/lane711/sonicjs-ai/tree/main/src/plugins/core-plugins",
    "license": "MIT",
    "category": "security",
    "tags": [
      "auth",
      "authentication",
      "users",
      "security",
      "rbac",
      "sessions"
    ],
    "dependencies": [],
    "settings": {
      "sessionTimeout": {
        "type": "number",
        "label": "Session Timeout (minutes)",
        "description": "Auto-logout after this many minutes of inactivity",
        "default": 60
      },
      "maxLoginAttempts": {
        "type": "number",
        "label": "Max Login Attempts",
        "description": "Lock account after this many failed login attempts",
        "default": 5
      },
      "requireStrongPasswords": {
        "type": "boolean",
        "label": "Require Strong Passwords",
        "description": "Enforce password complexity requirements",
        "default": true
      }
    },
    "hooks": {
      "onActivate": "activate",
      "onDeactivate": "deactivate"
    },
    "routes": [],
    "permissions": {
      "manage:users": "Manage users and accounts",
      "manage:roles": "Manage user roles",
      "manage:permissions": "Manage permission settings"
    }
  },

  'code-examples-plugin': {
    "id": "code-examples-plugin",
    "name": "Code Examples",
    "version": "1.0.0-beta.1",
    "description": "Code snippets and examples library with syntax highlighting and categorization",
    "author": "SonicJS Team",
    "homepage": "https://sonicjs.com/plugins/code-examples",
    "repository": "https://github.com/lane711/sonicjs-ai/tree/main/src/plugins/core-plugins",
    "license": "MIT",
    "category": "content",
    "tags": [
      "code",
      "examples",
      "snippets",
      "documentation"
    ],
    "dependencies": [],
    "settings": {},
    "hooks": {
      "onActivate": "activate",
      "onDeactivate": "deactivate"
    },
    "routes": [],
    "permissions": {
      "code-examples:manage": "Manage code examples"
    }
  },

  'database-tools': {
    "id": "database-tools",
    "name": "Database Tools",
    "version": "1.0.0-beta.1",
    "description": "Database management and administration tools including migrations, backups, and query execution",
    "author": "SonicJS Team",
    "homepage": "https://sonicjs.com/plugins/database-tools",
    "repository": "https://github.com/lane711/sonicjs-ai/tree/main/src/plugins/core-plugins/database-tools-plugin",
    "license": "MIT",
    "category": "development",
    "tags": [
      "database",
      "admin",
      "tools",
      "migrations",
      "backup"
    ],
    "dependencies": [],
    "settings": {},
    "hooks": {
      "onActivate": "activate",
      "onDeactivate": "deactivate"
    },
    "routes": [],
    "permissions": {
      "database:admin": "Administer database"
    }
  },

  'demo-login-plugin': {
    "id": "demo-login-plugin",
    "name": "Demo Login",
    "version": "1.0.0-beta.1",
    "description": "Quick demo login functionality for testing and demonstrations",
    "author": "SonicJS Team",
    "homepage": "https://sonicjs.com/plugins/demo-login",
    "repository": "https://github.com/lane711/sonicjs-ai/tree/main/src/plugins/core-plugins",
    "license": "MIT",
    "category": "utilities",
    "tags": [
      "demo",
      "testing",
      "development"
    ],
    "dependencies": [
      "core-auth"
    ],
    "settings": {},
    "hooks": {
      "onActivate": "activate",
      "onDeactivate": "deactivate"
    },
    "routes": [],
    "permissions": {}
  },

  'faq-plugin': {
    "id": "faq-plugin",
    "name": "FAQ Manager",
    "version": "1.0.0-beta.1",
    "description": "Frequently Asked Questions management plugin with categorization, search, and display templates",
    "author": "SonicJS Team",
    "homepage": "https://sonicjs.com/plugins/faq",
    "repository": "https://github.com/lane711/sonicjs-ai/tree/main/src/plugins/core-plugins",
    "license": "MIT",
    "category": "content",
    "tags": [
      "faq",
      "questions",
      "answers",
      "help",
      "support"
    ],
    "dependencies": [],
    "settings": {},
    "hooks": {
      "onActivate": "activate",
      "onDeactivate": "deactivate"
    },
    "routes": [],
    "permissions": {
      "faq:manage": "Manage FAQ content"
    }
  },

  'hello-world': {
    "id": "hello-world",
    "name": "Hello World",
    "version": "1.0.0-beta.1",
    "description": "A simple Hello World plugin demonstration",
    "author": "SonicJS Team",
    "homepage": "https://sonicjs.com/plugins/hello-world",
    "repository": "https://github.com/lane711/sonicjs-ai/tree/main/src/plugins/core-plugins/hello-world-plugin",
    "license": "MIT",
    "category": "utilities",
    "tags": [
      "demo",
      "example",
      "hello-world"
    ],
    "dependencies": [],
    "settings": {},
    "hooks": {
      "onActivate": "activate",
      "onDeactivate": "deactivate"
    },
    "routes": [],
    "permissions": {
      "hello-world:view": "View Hello World page"
    },
    "adminMenu": {
      "label": "Hello World",
      "icon": "hand-raised",
      "path": "/admin/hello-world",
      "order": 90
    }
  },

  'core-media': {
    "id": "core-media",
    "name": "Media Manager",
    "version": "1.0.0-beta.1",
    "description": "Core media upload and management system with support for images, videos, and documents. Includes automatic optimization, thumbnail generation, and cloud storage integration",
    "author": "SonicJS Team",
    "homepage": "https://sonicjs.com/plugins/core-media",
    "repository": "https://github.com/lane711/sonicjs-ai/tree/main/src/plugins/core-plugins",
    "license": "MIT",
    "category": "media",
    "tags": [
      "media",
      "uploads",
      "images",
      "files",
      "storage",
      "r2"
    ],
    "dependencies": [],
    "settings": {
      "maxFileSize": {
        "type": "number",
        "label": "Max File Size (MB)",
        "description": "Maximum upload file size in megabytes",
        "default": 10
      },
      "allowedFileTypes": {
        "type": "string",
        "label": "Allowed File Types",
        "description": "Comma-separated list of allowed extensions (e.g., jpg,png,pdf)",
        "default": "jpg,jpeg,png,gif,webp,pdf,mp4,mp3"
      },
      "autoOptimize": {
        "type": "boolean",
        "label": "Auto-Optimize Images",
        "description": "Automatically optimize images on upload",
        "default": true
      },
      "generateThumbnails": {
        "type": "boolean",
        "label": "Generate Thumbnails",
        "description": "Automatically generate thumbnails for images",
        "default": true
      }
    },
    "hooks": {
      "onActivate": "activate",
      "onDeactivate": "deactivate"
    },
    "routes": [],
    "permissions": {
      "manage:media": "Manage media library",
      "upload:files": "Upload files"
    },
    "adminMenu": {
      "label": "Media",
      "icon": "image",
      "path": "/admin/media",
      "order": 30
    }
  },

  'seed-data': {
    "id": "seed-data",
    "name": "Seed Data Generator",
    "version": "1.0.0-beta.1",
    "description": "Development tool for generating sample data and testing content. Useful for demos and development environments",
    "author": "SonicJS Team",
    "homepage": "https://sonicjs.com/plugins/seed-data",
    "repository": "https://github.com/lane711/sonicjs-ai/tree/main/src/plugins/core-plugins/seed-data-plugin",
    "license": "MIT",
    "category": "development",
    "tags": [
      "development",
      "testing",
      "seed-data",
      "demo"
    ],
    "dependencies": [],
    "settings": {},
    "hooks": {
      "onActivate": "activate",
      "onDeactivate": "deactivate"
    },
    "routes": [],
    "permissions": {
      "seed-data:generate": "Generate seed data"
    }
  },

  'testimonials-plugin': {
    "id": "testimonials-plugin",
    "name": "Testimonials",
    "version": "1.0.0-beta.1",
    "description": "Customer testimonials and reviews management with display widgets and ratings",
    "author": "SonicJS Team",
    "homepage": "https://sonicjs.com/plugins/testimonials",
    "repository": "https://github.com/lane711/sonicjs-ai/tree/main/src/plugins/core-plugins",
    "license": "MIT",
    "category": "content",
    "tags": [
      "testimonials",
      "reviews",
      "feedback",
      "ratings"
    ],
    "dependencies": [],
    "settings": {},
    "hooks": {
      "onActivate": "activate",
      "onDeactivate": "deactivate"
    },
    "routes": [],
    "permissions": {
      "testimonials:manage": "Manage testimonials"
    }
  },

  'workflow-plugin': {
    "id": "workflow-plugin",
    "name": "Workflow Engine",
    "version": "1.0.0-beta.1",
    "description": "Content workflow and approval system with customizable states, transitions, and review processes",
    "author": "SonicJS Team",
    "homepage": "https://sonicjs.com/plugins/workflow",
    "repository": "https://github.com/lane711/sonicjs-ai/tree/main/src/plugins/core-plugins/workflow-plugin",
    "license": "MIT",
    "category": "content",
    "tags": [
      "workflow",
      "approval",
      "review",
      "publishing",
      "collaboration"
    ],
    "dependencies": [],
    "settings": {
      "requireApproval": {
        "type": "boolean",
        "label": "Require Approval",
        "description": "Require approval before publishing content",
        "default": true
      },
      "notifyReviewers": {
        "type": "boolean",
        "label": "Notify Reviewers",
        "description": "Send notifications to reviewers when content needs approval",
        "default": true
      }
    },
    "hooks": {
      "onActivate": "activate",
      "onDeactivate": "deactivate"
    },
    "routes": [],
    "permissions": {
      "workflow:manage": "Manage workflow settings",
      "workflow:approve": "Approve content"
    }
  },

  'design': {
    "id": "design",
    "name": "Design System",
    "version": "1.0.0-beta.1",
    "description": "Design system management including themes, components, and UI customization. Provides a visual interface for managing design tokens, typography, colors, and component library.",
    "author": "SonicJS",
    "homepage": "https://sonicjs.com/plugins/design",
    "repository": "https://github.com/lane711/sonicjs-ai/tree/main/src/plugins/design",
    "license": "MIT",
    "category": "ui",
    "tags": [
      "design",
      "ui",
      "themes",
      "components",
      "customization"
    ],
    "dependencies": [],
    "settings": {
      "defaultTheme": {
        "type": "string",
        "label": "Default Theme",
        "description": "Default theme to use for the admin interface",
        "default": "dark",
        "options": [
          "light",
          "dark",
          "auto"
        ]
      },
      "customCSS": {
        "type": "boolean",
        "label": "Enable Custom CSS",
        "description": "Allow custom CSS overrides",
        "default": false
      }
    },
    "hooks": {
      "onActivate": "activate",
      "onDeactivate": "deactivate"
    },
    "routes": [
      {
        "path": "/admin/design",
        "method": "GET",
        "handler": "getDesignPage",
        "description": "Get design system management page"
      }
    ],
    "permissions": {
      "design.view": "View design system",
      "design.edit": "Edit design settings"
    },
    "adminMenu": {
      "label": "Design",
      "icon": "palette",
      "path": "/admin/design",
      "order": 80
    }
  }
} as const

/**
 * Get all plugin IDs
 */
export const PLUGIN_IDS = Object.keys(PLUGIN_REGISTRY) as ReadonlyArray<string>

/**
 * Get all core plugin IDs (plugins with is_core flag or in core directories)
 */
export const CORE_PLUGIN_IDS = PLUGIN_IDS.filter(id => {
  const manifest = PLUGIN_REGISTRY[id]
  return id.startsWith('core-') || id === 'design' || id === 'database-tools' || id === 'hello-world'
}) as ReadonlyArray<string>

/**
 * Get plugin manifest by ID
 */
export function getPluginManifest(id: string): PluginManifest | undefined {
  return PLUGIN_REGISTRY[id]
}

/**
 * Check if a plugin exists
 */
export function hasPlugin(id: string): boolean {
  return id in PLUGIN_REGISTRY
}

/**
 * Get all plugins by category
 */
export function getPluginsByCategory(category: string): PluginManifest[] {
  return PLUGIN_IDS
    .map(id => PLUGIN_REGISTRY[id])
    .filter((manifest): manifest is PluginManifest => manifest !== undefined && manifest.category === category)
}
