/**
 * Core Plugins Export
 *
 * Exports all core SonicJS plugins
 *
 * NOTE: The list of core plugins is now auto-generated from manifest.json files
 * See: src/plugins/plugin-registry.ts (auto-generated by packages/scripts/generate-plugin-registry.mjs)
 */

export { authPlugin, createAuthPlugin } from './auth'
export { mediaPlugin, createMediaPlugin } from './media'
export { analyticsPlugin, createAnalyticsPlugin } from './analytics'
export { testimonialsPlugin, createTestimonialPlugin } from './testimonials'
export { codeExamplesPlugin, createCodeExamplesPlugin } from './code-examples'
export { demoLoginPlugin } from './demo-login'
export { workflowPlugin, createWorkflowPlugin } from './workflow-plugin'
export { seedDataPlugin, createSeedDataPlugin } from './seed-data-plugin'
export { databaseToolsPlugin } from './database-tools-plugin'
export { helloWorldPlugin, createHelloWorldPlugin } from './hello-world-plugin'
export { quillEditorPlugin, createQuillEditorPlugin } from './quill-editor'
export { emailPlugin, createEmailPlugin } from './email-plugin'
export { otpLoginPlugin, createOTPLoginPlugin } from './otp-login-plugin'
export { turnstilePlugin } from './turnstile-plugin'
export { TurnstileService, verifyTurnstile, createTurnstileMiddleware } from './turnstile-plugin'

// Core plugins list - now imported from auto-generated registry
export const CORE_PLUGIN_IDS = [
  'core-auth',
  'core-media',
  'core-analytics',
  'testimonials-plugin',
  'code-examples-plugin',
  'demo-login-plugin',
  'workflow-plugin',
  'seed-data',
  'database-tools',
  'hello-world',
  'quill-editor',
  'email',
  'otp-login',
  'turnstile'
] as const

export type CorePluginNames = (typeof CORE_PLUGIN_IDS)[number]
