/**
 * Core Plugins Export
 *
 * Exports all core SonicJS plugins
 *
 * NOTE: The list of core plugins is now auto-generated from manifest.json files
 * See: src/plugins/plugin-registry.ts (auto-generated by packages/scripts/generate-plugin-registry.mjs)
 */

export { authPlugin, createAuthPlugin } from './auth'
export { mediaPlugin, createMediaPlugin } from './media'
export { analyticsPlugin, createAnalyticsPlugin } from './analytics'
export { testimonialsPlugin, createTestimonialPlugin } from './testimonials'
export { codeExamplesPlugin, createCodeExamplesPlugin } from './code-examples'
export { demoLoginPlugin } from './demo-login'
export { workflowPlugin, createWorkflowPlugin } from './workflow-plugin'
export { seedDataPlugin, createSeedDataPlugin } from './seed-data-plugin'
export { databaseToolsPlugin } from './database-tools-plugin'
export { helloWorldPlugin, createHelloWorldPlugin } from './hello-world-plugin'
export { quillEditorPlugin, createQuillEditorPlugin } from './quill-editor'
export { emailPlugin, createEmailPlugin } from './email-plugin'
export { otpLoginPlugin, createOTPLoginPlugin } from './otp-login-plugin'

// Core plugins list - now imported from auto-generated registry
import { CORE_PLUGIN_IDS } from '../plugin-registry'
export { CORE_PLUGIN_IDS as corePlugins, PLUGIN_REGISTRY } from '../plugin-registry'

export type CorePluginNames = (typeof CORE_PLUGIN_IDS)[number]